require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    PublicStorage: publicstorage
